// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentMarkManagement.Entities
{
    public partial class Departments
    {
        [Key]
        public int Department_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Department_name { get; set; }
    }
}