// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentMarkManagement.Entities
{
    public partial class student_Marks
    {
        [Key]
        public int Student_Marks_Id { get; set; }
        public int Student_Id { get; set; }
        public int Name { get; set; }
        public int Mark_1 { get; set; }
        public int Mark_2 { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        public double Total { get; set; }

        [ForeignKey(nameof(Student_Id))]
        [InverseProperty(nameof(student_Details.student_Marks))]
        public virtual student_Details Student { get; set; }
    }
}